#contexts
events {}

http {
    server {
        listen 80;

        absolute_redirect off; # port stripping off

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        # location /grafana/ {
        #     proxy_pass http://grafana:3000/;
        #
        #     proxy_set_header Host $host; # if http://homelab.local/grafana then host will be homelab.local instead of grafana:3000
        #     proxy_set_header X-Real-IP $remote_addr; # sends real ip addr of client for ratelimiting, logs, access control
        #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # appends current client ip in the ip-chain also for security, rate limiting etc.
        #     proxy_set_header X-Forwarded-Proto $scheme; # tells if http or https client connected with.
        #     # proxy_set_header X-Forwarded-Host $host; # Tells with which domain user accessed it. useful for applications using multiple domains.
        #     # proxy_set_header X-Forwarded-Port $server_port; # returns the server port of connection like 80, 3000, 443 etc;
        #     # proxy_set_header Upgrade $http_upgrade; # usefull for live websockets like videocalls, online code editors, live dashboards
        #     # proxy_set_header Connection "upgrade";
        # }
        #
        # location /prometheus/ {
        #     proxy_pass http://prometheus:9090/;
        #
        #     proxy_set_header Host $host; # if http://homelab.local/grafana then host will be homelab.local instead of grafana:3000
        #     proxy_set_header X-Real-IP $remote_addr; # sends real ip addr of client for ratelimiting, logs, access control
        #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # appends current client ip in the ip-chain also for security, rate limiting etc.
        #     proxy_set_header X-Forwarded-Proto $scheme; # tells if http or https client connected with.
        # }
        location /grafana/ {
            proxy_pass http://grafana:3000/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_buffering off;
            proxy_request_buffering off;
        }
        
        location /prometheus/ {
            proxy_pass http://prometheus:9090/;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
